sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "12"
before_script:
  - npm prune
script:
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npx semantic-release@15
